### PR TITLE
feat: support configured dependency cache directory

### PR DESCRIPTION
**Pull request by mikeshultz**
### What I did

Adds support for new `cache_folder` config var which defines where to place non-project dependencies.

Example config:

```yaml
name: ape-project

compile:
  cache_folder: .cache
```

Depends on: https://github.com/ApeWorX/ape/pull/1897

### How I did it

Replaces hard references to `.cache` to configuration.  Relies on base_dir for relative paths.

### How to verify it

Run against branch from above linked PR.

### Checklist

- [x] Passes all linting checks (pre-commit and CI jobs)
- [x] New test cases have been added and are passing
- [x] Documentation has been updated
- [x] PR title follows [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) standard (will be automatically included in the changelog)

### CODE REVIEW

**Review by fubuloubu — APPROVED** [review]
Does Vyper need a similar one?

**Comment by mikeshultz** [comment]
> Does Vyper need a similar one?

ape-vyper doesn't leverage the dependency cache folder and the `base_path` change seems to work just fine.

**Review by fubuloubu — APPROVED** [review]
looks good pending @antazoey approval

**Review by antazoey — APPROVED** [review]
ship it asap!

**Pull request merged**
